name: Coverage

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: xdebug
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --no-scripts

      - name: Run PHPUnit tests with coverage
        run: ./vendor/bin/phpunit --coverage-clover clover.xml
